trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Blazor 프로젝트 빌드
- script: |
    dotnet build $(Build.SourcesDirectory)\BlazorHelloWorld.csproj -c Release
  displayName: 'Build Blazor app'

# Blazor 앱 발행
- script: |
    dotnet publish $(Build.SourcesDirectory)\BlazorHelloWorld.csproj -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Blazor app'

# Azure Web App 배포
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1'
    appType: 'webAppWindows'
    appName: 'AzureDevOpsShua'
    runtimeStack: 'DOTNET|6.0' # 프로젝트와 일치하는 .NET 버전으로 수정
    package: $(Build.ArtifactStagingDirectory)
