trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: tree /f /a
  displayName: 'Show directory structure'

- script: dotnet build $(Build.SourcesDirectory)/src/BlazorHelloWorld.csproj -c Release
  displayName: 'Build Blazor app'

- script: dotnet publish $(Build.SourcesDirectory)/BlazorHelloWorld -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Blazor app'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1' # Azure 구독 이름 또는 서비스 연결 이름
    appType: 'webAppWindows' # 수정: 운영체제에 맞춰 변경
    appName: 'AzureDevOpsShua' # Azure Web App 이름
    runtimeStack: 'DOTNET|8.0' # 수정: .NET 버전에 맞춰 변경 (적절한 값으로 대체 필요)
    package: $(Build.ArtifactStagingDirectory) # 배포할 패키지의 위치